SELECT 
       t1.dtRef, 
       t1.idCliente,
       t1.idadeDias, 
       t1.qtdeAtivacaoVida,
       t1.qtdeAtivacaoD7,
       t1.qtdeAtivacaoD14,
       t1.qtdeAtivacaoD28,
       t1.qtdeAtivacaoD56,
       t1.qtdeTransacaoVida,
       t1.qtdeTransacaoD7,
       t1.qtdeTransacaoD14,
       t1.qtdeTransacaoD28,
       t1.qtdeTransacaoD56,
       t1.saldoVida,
       t1.saldoD7,
       t1.saldoD14,
       t1.saldoD28,
       t1.saldoD56,
       t1.qtdePontosPosVida,
       t1.qtdePontosPosD7,
       t1.qtdePontosPosD14,
       t1.qtdePontosPosD28,
       t1.qtdePontosPosD56,
       t1.qtdePontosNegVida,
       t1.qtdePontosNegD7,
       t1.qtdePontosNegD14,
       t1.qtdePontosNegD28,
       t1.qtdePontosNegD56,
       t1.qtdeTransacaoManha,
       t1.qtdeTransacaoTarde,
       t1.qtdeTransacaoNoite,
       t1.pctTransacaoManha,
       t1.pctTransacaoTarde,
       t1.pctTransacaoNoite,
       t1.QtdeTransacaoDiaVida,
       t1.QtdeTransacaoDiaD7,
       t1.QtdeTransacaoDiaD14,
       t1.QtdeTransacaoDiaD28,
       t1.QtdeTransacaoDiaD56,
       t1.pctAtivacaoMAU,
       t1.qtdeHorasVida,
       t1.qtdeHorasD7,
       t1.qtdeHorasD14,
       t1.qtdeHorasD28,
       t1.qtdeHorasD56,
       t1.avgIntervaloDiasVida,
       t1.avgIntervaloDiasD28,
       t1.qteChatMessage,
       t1.qteAirflowLover,
       t1.qteRLover,
       t1.qteResgatarPonei,
       t1.qteListadepresenca,
       t1.qtePresencaStreak,
       t1.qteTrocaStreamElements,
       t1.qteReembolsoStreamElements,
       t1.qtdeRPG,
       t1.qtdeChurnModel,
       t2.qtdeFrequencia,
       t2.descLifeCycleAtual,
       t2.descLifeCycleD28,
       t2.pctCurioso,
       t2.pctFiel,
       t2.pctTurista,
       t2.pctDesencantada,
       t2.pctZumbi,
       t2.pctReconquistado,
       t2.pctReborn,
       t2.avgFreqGrupo,
       t2.ratioFreqGrupo,
       t3.qtdeCursosCompletos,
       t3.qtdeCursosIncompletos,
       t3.carreira,
       t3.coletaDados2024,
       t3.dsDatabricks2024,
       t3.dsPontos2024,
       t3.estatistica2024,
       t3.estatistica2025,
       t3.github2024,
       t3.github2025,
       t3.iaCanal2025,
       t3.lagoMago2024,
       t3.machineLearning2025,
       t3.matchmakingTramparDeCasa2024,
       t3.ml2024,
       t3.mlflow2025,
       t3.pandas2024,
       t3.pandas2025,
       t3.python2024,
       t3.python2025,
       t3.sql2020,
       t3.sql2025,
       t3.streamlit2025,
       t3.tramparLakehouse2024,
       t3.tseAnalytics2024,
       t3.qtdDiasUltiAtividade

FROM fs_transacional AS t1

LEFT JOIN fs_life_cycle AS t2
ON t1.IdCliente = t2.IdCliente
AND t1.dtRef = t2.dtRef

LEFT JOIN fs_education AS t3
ON t1.IdCliente = t3.IdCliente
AND t1.dtRef = t3.dtRef

WHERE t1.dtRef = (SELECT MAX(dtRef) FROM fs_transacional)